# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(blank=True, max_length=255, null=True)),
                ('bb', models.CharField(blank=True, max_length=255, null=True)),
                ('cc', models.IntegerField(blank=True)),
                ('dd', models.IntegerField(blank=True)),
            ],
        ),
    ]
