# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='abc',
            managers=[
                ('create_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='abc',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 19, 2, 55, 6, 105146)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='ee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abc',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 19, 2, 55, 16, 320861)),
            preserve_default=False,
        ),
    ]
